### ISSUE TITLE
status of yapc site and yapc-org-website

### ISSUE THREAD

**Issue by rjbs** [tpf/webmaster#1]
Hello, this is a request for information!

I have a todo:  destroy repository https://github.com/tpf/yapc-org-website

Happy to, but:  is this duplicated elsewhere?

So a few questions:

1. is this destroyable?
2. what is the fate of yapc.org?  should it become perlconference.us?

Thanks!

**Comment by cromedome** [comment]
I am of the opinion that the repo can be archived. I don't want to lose the content. But leaving this as a functioning website... I am not sure I see the value of this.

Going forward, I think redirecting yapc.org to perlconferences.us is appropriate. YAPC is dead, long live YAPC!

I will float this at the next community leaders meeting - I expect to resolve this in short order however.

**Comment by toddr** [comment]
I'm not sure which repo it is but I just did some fixups in the last year. Some of the sites are repo driven right now.

**Comment by toddr** [comment]
The only persistent site I'm aware of is https://perlconference.us however that is US/NA focused. http://www.yapceurope.org/ exists but is more an admin site for coming/past conferences. They seem to do a different domain every year. It would be good to know how much traffic YAPC.org is getting.

**Comment by toddr** [comment]
To my knowledge, YAPC.org is being run by this repo. https://github.com/perlconference/yapc-org-website. It appears to be a fork of https://github.com/tpf/yapc-org-website. I would say that https://github.com/tpf/yapc-org-website can be deleted.

**Comment by toddr** [comment]
If someone needs access, please feel free to reach out to me.

**Comment by toddr** [comment]
Barring any objections, I'm going to delete the duplicate repo https://github.com/tpf/yapc-org-website in 30 days.

**Comment by toddr** [comment]
This repo is now gone.
