### ISSUE TITLE
Redirect donate.perlfoundation.com to https://www.perlfoundation.org/donate.html

### ISSUE THREAD

**Issue by toddr** [tpf/webmaster#2]
donate.perlfoundation.com is unmaintained and replaced by content at the perlfoundation.org website.

We'd like the following permanent redirects for the site:

https://donate.perlfoundation.org/prospectus.html -> https://www.perlfoundation.org/donation-prospectus.html
The rest should just go to https://www.perlfoundation.org/donate.html

**Comment by rjbs** [comment]
(Yes, please, just came across this myself.  Ugh.)

**Comment by autarch** [comment]
This is long done.
