### ISSUE TITLE
Donation page missing currency

### ISSUE THREAD

**Issue by andrewsolomon** [tpf/webmaster#4]
When a user is filling in the form to donate, they get to enter the amount but there's no indication of the currency. This is the case for both

company:

https://perlfoundation.z2systems.com/np/clients/perlfoundation/donation.jsp?&constTypeFlag=org

and individual:

https://perlfoundation.z2systems.com/np/clients/perlfoundation/donation.jsp?

**Comment by cromedome** [comment]
TPF treasurer added USD to these forms. Closing.
